### ISSUE TITLE
Epoch error in beacon server and path server

### ISSUE THREAD

**Issue by FR4NK-W** [netsec-ethz/scion#1279] opened 2017-10-10 09:16 UTC
relative_epoch = proof.epoch % n_epochs
 [CRITICAL] (MainThread) ZeroDivisionError: integer division or modulo by zero

Beacon server and path server crash after running for a few hours, because a modulo by zero happens in their use of python/lib/crypto/hash_tree.py

Attached are the debug and error logs of the path server and the beacon server
[bs_and_ps_DEBUG-ERROR.zip](https://github.com/netsec-ethz/scion/files/1371249/bs_and_ps_DEBUG-ERROR.zip)

**Comment by klausman** [comment] 2017-10-10 09:20
What commit ID are you on?

**Comment by FR4NK-W** [comment] 2017-10-10 10:34
@klausman commit 516a7d84191f0f259772e33dc07ad712759e4294
So the latest one.
The rest is also pretty standard:
~/go/src/github.com/netsec-ethz/scion$ uname -a
Linux scionlab-**** 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~/go/src/github.com/netsec-ethz/scion$ cat /etc/*-releaseDISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by FR4NK-W** [comment] 2017-10-10 10:34
Let me now what other info might be helpful

**Comment by klausman** [comment] 2017-10-10 10:38
@shitz claims that this was fixed in a commit recently, I'll let him weigh in on this.

**Comment by shitz** [comment] 2017-10-10 12:06
I thought you were running this locally, but the problem is that the infrastructure in AS `1-6` is running on a commit that doesn't set this value if none is specified in the config. @ercanucan should either update to a newer version, where this value will get a reasonable default value, or regenerate the `as.yml` config with the generator. In any case, I will create a PR to prevent crashing a service.

**Comment by kormat** [comment] 2017-11-30 09:37
I believe that this is handled now. #1342 should also remove a class of validation bugs.

**Closed by kormat** 2017-11-30 09:37 UTC
